name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/${{ secrets.DROPLET_USER }}/trading_bot
          git pull origin main
          pip install -r requirements.txt
          sudo systemctl restart trading-bot.service